### ISSUE TITLE
E57 transformation do not preserve unrelated E57 structure

### ISSUE THREAD

**Issue by nh2** [CloudCompare/CloudCompare#1711]
When I have an E57 file that has e.g. `images2D` contents such as

```
images2D:
- acquisitionDateTime:
    dateTimeValue: 1234567890.123456
    isAtomicClockReferenced: 0
  associatedData3DGuid: '0000000000000001'
  guid: '0000000000000000'
  name: abababab-1234-1234-1234-abababababab
  pinholeRepresentation:
    focalLength: 0.012284999846809221
    imageHeight: 4096
    imageWidth: 4096
    jpegImage: <BlobNode 'jpegImage'>
    pixelHeight: 6.0e-06
    pixelWidth: 6.0e-06
    principalPointX: 2047.5
    principalPointY: 2047.5
  pose:
    rotation:
      w: -0.4721114569930048
      x: -0.47211145699300555
      y: 0.5264131193045462
      z: 0.5264131193045452
    translation:
      x: 100.0
      y: 200.0
      z: 300.0
  sensorModel: CycloneRegister360
```

and I shift the whole point cloud (e.g. using CloudCompare's CLI) then the `images2D` is not preservered, but data is lost:

```
images2D:
- associatedData3DGuid: '{0fec4a90-4125-4ac6-b2f9-51aa4dfc14dc}'
  guid: '{eabf7ef9-55a5-42b4-8b87-e6a41b40ab0a}'
  name: abababab-1234-1234-1234-abababababab
  visualReferenceRepresentation:
    imageHeight: 4096
    imageWidth: 4096
    pngImage: <BlobNode 'pngImage'>
```

Here, many fields were lost, and the `associatedData3DGuid` and `guid` fields were changed.

**How to reproduce**

1. Transform an E57 file using e..g the CloudCompare CLI `CloudCompare -SILENT -AUTO_SAVE OFF -O -GLOBAL_SHIFT 100 200 300 in.e57 -DROP_GLOBAL_SHIFT -C_EXPORT_FMT E57 -SAVE_CLOUDS FILE out.e57

**Expected behaviour**

CloudCompare does not touch the E57 data that it does not need to modify for the transformation, thus preserving it.

**Your environment**
 - CC Version (or git hash/tag): `2021-10-14`
 - OS & Version: Linux
